### ISSUE TITLE
Pick up Dead Rooster Crash (Butchering Compat)

### ISSUE THREAD

**Issue by LarekFlynn** [sekelsta/detailedanimals#3]
Killed a freshly spawned rooster(new texture probably) and clicked to pick up for butchery and got a crash:

Running on 64 bit Windows 10.0.19045.0 with 32711 MB RAM
Game Version: v1.19.8 (Stable)
10/10/24 12:51:07 AM: Critical error occurred in the following mod: butchering@1.6.8

<details><summary>Loaded Mods:</summary>
<p>

detonateredux@1.1.1, degrees1499@1.0.0, acorns@0.5.3, aculinaryartillery@1.2.1, advancedsmithing@1.3.0, africanmonitorlizards@1.0.7, Armorlite@1.1.0, arrowheadsrecovery_fork@1.0.0, asianmonitorlizards@1.0.1, atwatersedge@1.5.0, axleinblocks@1.19.8-rc.1, balancedthirst@0.0.43, bamboom@0.2.1, bandedgeckos@1.2.0, beardeddragons@1.0.0, bearhidepatches@1.1.1, betterbricks@1.1.1, bettercompost@1.0.2, easyjam@1.0.0, bf@0.0.2, bettershears@1.0.0, irregularguyboltheadsrecovery@1.0.1, explosivevanvar@0.0.5, brigandinerebalance@1.0.0, buckets_stack_to_5@1.0.1, buzzwords@1.7.0, cairns11bigcairn@1.1.0, cellardoor@1.4.0, charcoalpitrebalance@1.0.1, chargedjump@1.0.0, chiblocksel@1.0.5, chiseltools@1.12.10, claycasting@1.2.0, clayfromdirt@1.0.3, clickuptorches@1.1.1, Clothez@1.0.0, compass2@3.0.0, landformoverhaul@0.0.2, coreblast@0.1.2, crackedrockweak@1.0.0, craftingjonas@1.0.6, creaturescan@1.0.10, cumanhelmet@0.7.5, cutthefat@1.0.1, decor@1.1.6, directstrongtannin@1.0.0, distillationinfo@1.0.0, dont-place-sticks@1.0.1, dryable_ground_storage@1.0.0, DrystoneParity@1.0.0, dye_recipes_fix@1.1.0, eldritchcuteclothing@1.0.2, ensatinas@1.0.0, entitiesinteract@1.0.11, evaporite@1.0.0, explosive@0.0.5, extendedcrafts@1.1.4, morecropsfix@1.0.6, fernslikegrass@1.1.0, fibersfromtwine@1.0.1, fieldsofgold@2.1.6, firewoodfrombamboo@1.0.0, fixture@1.0.2, flourbags@1.0.5, caninae@1.0.16, capreolinae@1.1.5, casuariidae@1.0.8, dinornithidae@0.7.0, machairodontinae@1.0.9, manidae@1.0.2, pantherinae@1.1.9, rhinocerotidae@1.0.3, sirenia@1.0.5, free_stone_drops_when_broken@1.0.1, geoaddons@1.3.5, giantgouramis@1.0.2, gildedsteel@1.0.5, hammercrushed@1.0.0, HangingOilLamps@1.0.1, healthiertrees@1.0.0, hideandfabric-net7u@1.3.1, icyexc@1.0.0, ifozclothes@1.1.1, immersivecorpsedrop@1.0.2, immersiveorecrush@1.0.0, indappledgroves@0.8.5, ingotheating@1.0.2, japanesemod@1.3.6, juicyores@1.0.0, knappingmastery@1.0.1, knobtailedgeckos@1.2.1, lanternliner@0.1.0, lanternpost@1.0.8, leopardgeckos@1.2.2, lithocraft@0.3.3, longtermfood@0.0.5, meatup@0.1.1, meltingpp@1.0.3, metaldetector@1.0.1, millwright@1.1.7, molds@0.0.9, morecrystals@1.2.0, moredrygrass@0.2.0, morenails@1.1.0, moreparchment@1.0.0, MoreTorchHolders@1.0.0, mycodiversity@1.0.2, nacatfish@1.0.1, nadarters@2.0.0, nasalamanders@1.0.0, naturalclay@1.1.1, newworldgianttortoises@1.1.1, pondfrogsiii@1.2.3, newzealandfrogs@1.1.1, unochre@1.2.0, oils@1.2.2, pondfrogsi@1.2.3, orepulverizer@1.1.1, pacificnewts@1.3.1, PartialLandslides@1.0.0, peacockbasses@1.1.2, pipeleaf@1.8.0, primitivesurvival@3.6.5, proximityprospectingpick@1.0.1, unpfix@1.0.0, quicklimepk@1.0.0, rainfrogs@1.2.1, rawhideclothrot@0.0.1, bpip@0.0.9, realshingles@1.0.2, ripened_wild_crops@1.0.0, rlmoonsun@0.1.2, rope-bridges@1.1.0, ropebridgescompatibility@1.1.0, russianmod@1.1.1, saltandsands@1.0.2, salty@1.0.1, scatastrophe@1.1.2, she1fish@1.2.1, shepherdmod@1.0.2, simplerails@1.0.0, speararrowheadbits@1.1.0, SpeedBoostCraftables@1.0.2, spiderwebtwine@0.0.1, sticksfromfirelogs@1.3.0, superfuelresumed@2.1.3, swordz@1.1.8, swordzcompat@1.0.1, litbrig@0.5.0, thatchexpanded@1.1.1, truesunfishes@1.1.2, untamedwildsursidae@1.0.8, usefuldrifterloot@1.1.0, viesblocks@2.4.12, game@1.19.8, wallpaperblocks@2.0.0, wallpaper@1.0.0, warriordrink@1.0.2, zoombuttonreborn@1.9.0, abcsreborn@0.2.2, alchemycompat@1.0.0, alchemy@1.6.34, all_crates_matter@1.0.0, ancienttools@1.5.18, animationmanagerlib@0.8.8, apelanterns@1.0.0, apewindows@1.1.0, wrenchroof@1.1.0, artofgrowing@0.0.4, augplantlib@0.0.3, flags@0.33.1, barreldough@2.0.0, beartrap@1.1.1, bedspawnv2@1.2.0, beehivekiln@1.6.1, beltcraft@1.0.0, betterbloomeriesreborn@1.0.5, bettercaveart@1.1.1, betterentityinteraction@1.0.0, betterfirepit@1.1.4, betterfpcamera@1.2.0, betterhewnfencegates@1.0.0, betterstonepath@1.0.3, biggercellars@1.0.0, blacksmithenhancements@1.0.5, bodyheatbarfix@1.0.1, butchering@1.6.8, butterflycases@1.0.1, cancrops@0.2.3, canjewelry@0.3.6, carryon@1.7.4, charcoalpitdoor@1.0.0, chickenfeed@1.1.3, clearerquartzfix@1.0.0, clipfix@1.0.7, commonlib@2.5.0-rc.2, composter@1.1.0, Crateful@1.2.8, creaturekilledby@1.0.0, crosscomme@1.0.10, cuniculture@1.0.2, danacancook@0.2.3, danatweaks@3.2.2, darkerdrifterspawns@1.0.1, deconstructchutes@1.0.1, displaycasewall@1.0.3, doubleslabs@0.1.1, electricity@0.0.11, evenjugincrements@1.0.0, expandedfoods@1.7.2, extrachutes@1.0.0, extrainfo@1.8.1, fancyclouds2d@1.1.0, fancyplanters@1.2.0, helfavorite@0.3.5, fenceclimbable@1.0.0, fieldsofsalt@1.2.1, foodshelves@1.3.1, fromgoldencombs@1.6.3, fruitpressmashfix@1.0.0, furniturelibrary@1.0.11, gggenchem@0.2.0, golb@1.0.0, gourmand@1.2.4, hangingbaskets@1.1.0, hardcoreutilities@1.2.0, heatretention@1.0.2, herbarium@1.3.0, highfert@1.0.0, hit@2.1.2, hydrateordiedrate@1.3.9, immersivetpscamera@1.0.5, improvedhandbookrecipes@1.0.0, itemframe@1.0.0, jayuscookbook@1.0.2, kegrevivedagain@1.1.0, kevinsfurniture@1.2.0, kscartographytable@1.0.1, lc@1.0.0, labeledtrunk@1.0.5, lavoisier@1.3.0, lib2d@1.0.0, lichenredux@1.8.3, liquidcontainers@1.2.0, lubricant@1.2.2, maltiezbows@1.0.4, manualdough@1.0.2, manualscraping@1.0.0, medievalexpansion@3.13.1, metaltongs@1.1.3, mio@0.9.5, meteoricexpansion@1.2.5, middleclicktostow@1.0.0, mif@1.0.1, minimalcompass@1.0.0, moreanimals@1.3.5, morepiles@1.5.0, moreplaster@1.0.2, mouse4and5@2.0.0, mcrate@1.2.1, mushroomz@1.0.2, naturalnight@2.1.0, nodrunkenshaking@1.0.1, spearexpantion@0.1.9, particlesplus@1.1.0, passthruchutes@1.0.1, simplewinddirectionpelagus@1.0.0, petai@2.2.6, pickbars@1.0.0, pigfeed@1.0.4, pileful@1.1.5, pomshadercache@1.1.1, postsandbeams@1.3.2, claywheel@1.1.1, powdermanufacturing@0.0.2, precisepickedup@1.0.0, RareDenseOres@0.2.6, redbricktweak@1.0.0, resurgencepack@1.6.0, rivers@3.1.0, rockstratavariety@0.0.1, sailboat@1.3.1, scarecrow@1.5.1, seashellore@1.0.0, shovelimpervioustosnow@1.0.0, simplecloth@1.0.2, simplestep@1.1.7, simpletailoring@1.0.1, somethinginthewater@1.2.4, starvation@1.0.5, steamandpower@1.6.3, steelanvil@1.0.0, stillnecessaries@1.1.2, stonebakeoven@1.1.3, survivalexpanded@0.2.3, tarmor@0.2.2, thecritterpack@0.9.1, thirdperson_crosshair@1.0.0, toolworks@1.8.1, trailmod@1.0.8, tstools@2.1.2, usefulstuff17@1.3.2, vanillacratecompatibility@1.0.0, vanvar@5.0.4, versionchecker@1.0.0, creative@1.19.8, vsimgui@1.1.5, survival@1.19.8, warmarmor@1.1.0, wgmt@1.0.2, whatbagwasthatagain@1.0.1, wildfarmingrevival@1.2.5, workbenchexpansion@1.8.0, xlib@0.8.6, yummyfoods@1.0.4, alchemistry@1.0.2, metalrecovery@0.1.19-pre.1, beehivekilnwithclay@1.0.0, betterbamboo@1.0.2, bookbinders@1.1.1, bugnetcompatibility@1.0.1, bullseye-continued@2.5.8, butcheringbloodsausages@1.0.1, cancropsprimitivesurvivalcompat@1.0.3, cokemakesense@1.0.1, configlib@1.3.13, constructionsupport@0.1.2, detailedanimals@0.1.2, dowsedinsalt@1.0.0, electricityaddon@0.0.7, electricityextensions@0.0.7, em@2.7.0, extraoverlays@1.4.0, feverstonehorses@1.6.1, flammablefirestarter@1.0.1, fruitpresstweaked@1.0.1, fsmlib@0.4.5, glassmaking@1.4.0, justchairs@0.0.1, laverace@1.0.3, morecandles@1.2.2, morefloors@2.1.1, newworldcrops@0.0.8, onestick@1.0.1, pickupartist@0.2.0, pickupfast@1.0.2, plankable-nmnd@0.1.2, porridgewithmilk@1.0.0, helquickstack@0.4.2, RedDyeFromBerries@1.1.1, sandwich@1.2.0, shearlib@1.0.0, slanted_display_cases@1.3.2, expandedfoodscheese@1.0.0, stainedbeams@1.0.0, cookie12000stickbeam@1.1.0, stonepiles@1.1.2, stonequarry@3.3.1, talderzeit@0.1.2, toolworksadditions@1.3.2, treetapping@1.0.0, Uncrustables@1.0.0, vanity@2.2.0, vsrecipes@1.2.3, wattleworldrevised@1.1.0, wildcraftfruit@1.2.2, wildcraftherb@0.0.1, wildcrafttree@1.2.0, xinvtweaks@1.6.6, xskills@0.8.8, bricklayers@2.5.6, cancropsxskillscompat@1.0.7, chickenfeedwildcraftfruitcompat@1.0.0, maltiezcrossbows@0.3.11, maltiezfirearms@0.5.4, maltiezspears@0.1.6, maltiezswords@0.0.1, statushudcont@2.1.1, tailorsdelight@1.7.1, ashes@1.0.0, wildberrydye@0.0.1, wool@1.2.0, xskillscatchablepatch@1.1.1, banners@0.1.1, bricklayerglassmakingcompat@1.0.2, dressmakers@1.4.0, upholstery@1.0.1

</p>
</details> 

System.Exception: Could not find butchering item deadchicken-male-6-dead
   at Butchering.EntityBehaviorButcherable.OnInteract(EntityAgent byEntity, ItemSlot itemslot, Vec3d hitPosition, EnumInteractMode mode, EnumHandling& handled) in C:\Users\daifi\Desktop\Vintage Story Modding\butchering\butchering\src\EntityBehaviors\BehaviorButcherable.cs:line 50
   at Vintagestory.API.Common.EntityAgent.OnInteract(EntityAgent byEntity, ItemSlot slot, Vec3d hitPosition, EnumInteractMode mode) in VintagestoryApi\Common\Entity\EntityAgent.cs:line 287
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsNoBlockSelected_Patch1(SystemMouseInWorldInteractions this, Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 89
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1013
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by sekelsta** [comment]
Hey, thanks for letting me know but I don't think I can fix this from my end. I've passed this on to CaptainOats as it's happening in Butchery's code and would have to be fixed there.
