### ISSUE TITLE
Missing animal names for ver 0.3.0

### ISSUE THREAD

**Issue by kamipixel** [sekelsta/detailedanimals#4]
I'm using the latest update, with the corresponding game update, and no animal name is showing up. that bar is completely empty of text. all other information is there in the little text box, but not that one line. this is for every animal affected by the mod no matter if alive or dead. i tested with a new save and just the one mod on and i get the same results
![name_bug](https://github.com/user-attachments/assets/8c3d9713-1866-4601-8f88-3a5d1feabf5f)

**Comment by sekelsta** [comment]
Fixed in 0.3.1, thank you!
