### ISSUE TITLE
Lang file updated

### ISSUE THREAD

**Issue by BradyThe** [sekelsta/detailedanimals#5]
https://gitlab.com/Brady_The/vintage-story-localization/-/tree/main/Truth%20and%20Beauty%20-%20Detailed%20Animals

Suggestion: Add a remark to the changelog that new localization lines have been added. That way it's easier for me to track any changes. Cheers.

**Comment by sekelsta** [comment]
Thank you, now merged in.

**Comment by sekelsta** [comment]
Next release will have new localization lines matching what is currently on main.
